staging/staging/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('unyou.urls')),
]

staging/unyou/urls.py
from django.urls import path
from .views import UnyouFilterView, UnyouDetailView, UnyouCreateView, UnyouUpdateView, UnyouDeleteView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 一覧画面
    path('',  UnyouFilterView.as_view(), name='index'),
    # 詳細画面
    path('detail/<int:pk>/', UnyouDetailView.as_view(), name='detail'),
    # 登録画面
    path('create/', UnyouCreateView.as_view(), name='create'),
    # 更新画面
    path('update/<int:pk>/', UnyouUpdateView.as_view(), name='update'),
    # 削除画面
    path('delete/<int:pk>/', UnyouDeleteView.as_view(), name='delete'),
    ]


staging/unyou/models.py
from django.db import models

class Unyou(models.Model):
    id = models.CharField(db_column='id', primary_key=True, max_length=100, blank=True, null=False)
    lbc = models.CharField(verbose_name='LBC',db_column='LBC', max_length=100, blank=True, null=True)  # Field name made lowercase.
    main_lbc = models.CharField(db_column='Main_LBC', max_length=100, blank=True, null=True)  # Field name made lowercase.
    parent_lbc = models.CharField(db_column='Parent_LBC', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_top_lbc1 = models.CharField(db_column='group_top_LBC1', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_lbc1 = models.CharField(db_column='group_LBC1', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_lbc2 = models.CharField(db_column='group_LBC2', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_lbc3 = models.CharField(db_column='group_LBC3', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_lbc_id1 = models.CharField(db_column='group_LBC_id1', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_lbc_id2 = models.CharField(db_column='group_LBC_id2', max_length=100, blank=True, null=True)  # Field name made lowercase.
    group_lbc_id3 = models.CharField(db_column='group_LBC_id3', max_length=100, blank=True, null=True)  # Field name made lsowercase.
    listing_id = models.CharField(db_column='Listing_id', max_length=100, blank=True, null=True)  # Field name made lowercase.
    listing_name = models.CharField(db_column='Listing_name', max_length=100, blank=True, null=True)  # Field name made lowercase.
    ticker_symbol = models.CharField(db_column='Ticker_symbol', max_length=100, blank=True, null=True)  # Field name made lowercase.
    periodic_report_number = models.CharField(max_length=100, blank=True, null=True)
    company_status_id = models.CharField(max_length=100, blank=True, null=True)
    company_status_name = models.CharField(max_length=100, blank=True, null=True)
    office_status_id = models.CharField(max_length=100, blank=True, null=True)
    office_status_name = models.CharField(max_length=100, blank=True, null=True)
    merged_lbc = models.CharField(db_column='merged_LBC', max_length=100, blank=True, null=True)  # Field name made lowercase.
    #bankruptcy_date = models.DateField(blank=True, null=True)
    legal_personality = models.CharField(max_length=100, blank=True, null=True)
    company_name = models.CharField(verbose_name='会社名',max_length=100, blank=True, null=True)
    legal_personality_place = models.CharField(max_length=100, blank=True, null=True)
    company_name_sub = models.CharField(max_length=100, blank=True, null=True)
    office_name = models.CharField(max_length=100, blank=True, null=True)
    zipcode = models.CharField(max_length=100, blank=True, null=True)
    prefectures_id = models.CharField(max_length=100, blank=True, null=True)
    municipality_id = models.CharField(max_length=100, blank=True, null=True)
    prefectures_name = models.CharField(max_length=100, blank=True, null=True)
    municipality_name = models.CharField(max_length=100, blank=True, null=True)
    town_name = models.CharField(max_length=100, blank=True, null=True)
    city_block = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    building = models.CharField(max_length=100, blank=True, null=True)
    telephone_number = models.CharField(max_length=100, blank=True, null=True)
    fax_number = models.CharField(max_length=100, blank=True, null=True)
    offices_number = models.CharField(max_length=100, blank=True, null=True)
    #establishment_year = models.DateTimeField()
    capital = models.CharField(max_length=100, blank=True, null=True)
    employee_number = models.CharField(max_length=100, blank=True, null=True)
    current_term_settlement = models.CharField(max_length=100, blank=True, null=True)
    sales_current_term = models.CharField(max_length=100, blank=True, null=True)
    sales_ratio = models.CharField(max_length=100, blank=True, null=True)
    profit_term = models.IntegerField(db_column='Profit_term', blank=True, null=True)  # Field name made lowercase.
    profit_ratio = models.CharField(max_length=100, blank=True, null=True)
    dividend_term = models.CharField(max_length=100, blank=True, null=True)
    representative_position = models.CharField(db_column='Representative_position', max_length=100, blank=True, null=True)  # Field name made lowercase.
    representatives_name = models.CharField(db_column='Representatives_name', max_length=100, blank=True, null=True)  # Field name made lowercase.
    representatives_name_sub = models.CharField(db_column='Representatives_name_sub', max_length=100, blank=True, null=True)  # Field name made lowercase.
    industry_id1 = models.IntegerField(db_column='Industry_id1', blank=True, null=True)  # Field name made lowercase.
    industry_name1 = models.CharField(max_length=100, blank=True, null=True)
    industry_id2 = models.IntegerField(db_column='Industry_id2', blank=True, null=True)  # Field name made lowercase.
    industry_name2 = models.CharField(max_length=100, blank=True, null=True)
    industry_id3 = models.IntegerField(db_column='Industry_id3', blank=True, null=True)  # Field name made lowercase.
    industry_name3 = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(db_column='URL', max_length=100, blank=True, null=True)  # Field name made lowercase.
    telephone_call_check = models.CharField(max_length=100, blank=True, null=True)
    relocation_number = models.CharField(db_column='Relocation_number', max_length=100, blank=True, null=True)  # Field name made lowercase.
    fax_call_check = models.CharField(max_length=100, blank=True, null=True)
    relocation_fax = models.CharField(max_length=100, blank=True, null=True)
    company_type_id = models.CharField(max_length=100, blank=True, null=True)
    company_type_name = models.CharField(max_length=100, blank=True, null=True)
    foreign_owned_id = models.CharField(db_column='Foreign_owned_id', max_length=100, blank=True, null=True)  # Field name made lowercase.
    #survey_date = models.DateField(db_column='Survey_date', blank=True, null=True)  # Field name made lowercase.
    number_of_employees = models.IntegerField(blank=True, null=True)
    sales = models.CharField(max_length=100, blank=True, null=True)
    profit = models.CharField(max_length=100, blank=True, null=True)
    overseas_expansion_company = models.CharField(db_column='Overseas_expansion_company', max_length=100, blank=True, null=True)  # Field name made lowercase.
    a = models.IntegerField(db_column='A', blank=True, null=True)  # Field name made lowercase.
    b = models.IntegerField(db_column='B', blank=True, null=True)  # Field name made lowercase.
    c = models.IntegerField(db_column='C', blank=True, null=True)  # Field name made lowercase.
    d = models.IntegerField(db_column='D', blank=True, null=True)  # Field name made lowercase.
    e = models.IntegerField(db_column='E', blank=True, null=True)  # Field name made lowercase.
    f = models.IntegerField(db_column='F', blank=True, null=True)  # Field name made lowercase.
    g = models.IntegerField(db_column='G', blank=True, null=True)  # Field name made lowercase.
    h = models.IntegerField(db_column='H', blank=True, null=True)  # Field name made lowercase.
    i = models.IntegerField(db_column='I', blank=True, null=True)  # Field name made lowercase.
    j = models.IntegerField(db_column='J', blank=True, null=True)  # Field name made lowercase.
    k = models.IntegerField(db_column='K', blank=True, null=True)  # Field name made lowercase.
    l = models.IntegerField(db_column='L', blank=True, null=True)  # Field name made lowercase.
    sub11 = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.company_name

    class Meta:
        managed = False
        db_table = 'unyou'
        verbose_name = "__all__"
        verbose_name_plural = "__all__"

# Create your models here.

staging/unyou/forms.py
from django import forms
from .models import Unyou


class UnyouForm(forms.ModelForm):

    class Meta:
        model = Unyou
        fields = ('lbc','main_lbc','company_name','telephone_number')
        widgets = {
                    'lbc': forms.NumberInput(attrs={'min':1}),
                    'main_lbc': forms.NumberInput(attrs={'min':1}),
                    'company_name': forms.TextInput(attrs={'placeholder':'記入例：株式会社ネオキャリア'}),
                    'telephone_number': forms.NumberInput(attrs={'min':1}),
                  }

staging/unyou/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from pure_pagination.mixins import PaginationMixin
from .models import Unyou
from .filters import UnyouFilter
from .forms import UnyouForm


class UnyouFilterView(LoginRequiredMixin, PaginationMixin, FilterView):
    model = Unyou
    filterset_class = UnyouFilter
    paginate_by =25
    object = Unyou
 # クエリ未指定の時に全件検索を行うために以下のオプションを指定（django-filter2.0以降）
strict = False

# pure_pagination用設定


# 検索条件をセッションに保存する or 呼び出す
def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)


# 詳細画面
class UnyouDetailView(LoginRequiredMixin, DetailView):
        model = Unyou

# 登録画面
class UnyouCreateView(LoginRequiredMixin, CreateView):
        model = Unyou
        form_class = UnyouForm
        success_url = reverse_lazy('index')

# 更新画面
class UnyouUpdateView(LoginRequiredMixin, UpdateView):
        model = Unyou
        form_class = UnyouForm
        success_url = reverse_lazy('index')
# 削除画面
class UnyouDeleteView(LoginRequiredMixin, DeleteView):
        model = Unyou
        success_url = reverse_lazy('index')

staging/unyou/templates/unyou/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>つかわきアプリ</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{% static "app/css/app.css" %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">つかわきアプリ</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-unyou">
                    <a class="nav-link" href="/admin">管理サイト</a>
                </li>
                <li class="nav-unyou">
                    <a class="nav-link" href="/admin/logout">ログアウト</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

staging/unyou/templates/unyou/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-unyou">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled page-unyou">
        <span class="page-link">&laquo;</span>
    </li>
    {% endif %}
    {% for page in page_obj.pages %}
    {% if page %}
    {% ifequal page page_obj.number %}
    <li class="active page-unyou">
        <span class="page-link">{{ page }}
            <span class="page-link sr-only">(current)</span>
        </span>
    </li>
    {% else %}
    <li class="page-unyou">
        <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
    </li>
    {% endifequal %}
    {% else %}
    <li class="page-unyou">
            <a class="page-link">…</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-unyou">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled page-unyou">
        <span class="page-link">&raquo;</span>
    </li>
    {% endif %}
</ul>

staging/unyou/templates/unyou/unyou_card.html
<div class="row">
    <div class="col-3">
        <p>LBC</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.lbc }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>社名</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.company_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>メインLBC</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.main_lbc }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>グループトップ</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.group_top_lbc1 }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>子会社</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.parent_lbc }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>法人格</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.legal_personality}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>住所</p>
    </div>
    <div class="col-9">
        <p>{{unyou.prefectures_name}}{{ unyou.municipality_name}}{{ unyou.town_name}}{{unyou.city_block}}{{unyou.address}}{{unyou.building}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>上場区分</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.listing_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>有価証券報告書ナンバー</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.periodic_report_number}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>事業状況</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.office_status_name}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>電話番号</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.telephone_number}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>事業所数</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.offices_number}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>資本金</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.capital}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>従業員数</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.employee_number}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期売上高</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.sales_current_term}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期売上高前年比率</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.sales_ratio}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期利益</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.profit_term}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期利益前年比率</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.profit_ratio}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期配当金</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.dividend_term}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>代表者役職</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.representative_position}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>代表者名</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.representatives_name}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>業種名称1</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.industry_name1}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>業種名称2</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.industry_name2}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>業種名称3</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.industry_name3}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>URL</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.url}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期利益</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.profit_term}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>企業区分</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.company_type_name}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>従業員数</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.number_of_employees}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>売上高</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.sales}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>当期利益</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.profit}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>海外進出企業フラグ</p>
    </div>
    <div class="col-9">
        <p>{{ unyou.overseas_expansion_company}}</p>
    </div>
</div>

staging/unyou/templates/unyou/unyou_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
<div class="container">
    <h2 class="text-center">データ削除</h2>
    <p>このデータを削除します。よろしいですか？</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
        {% include "./unyou_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

staging/unyou/templates/unyou/unyou_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h2 class="text-center">詳細表示</h2>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
        </div>
    </div>
    <!--  -->
    {% include "./unyou_card.html" %}
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
        </div>
    </div>
</div>
{% endblock %}

staging/unyou/templates/unyou/unyou_filter.html
{% extends "./_base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">検索条件</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="filter" method="get">
                    <div class="modal-body">
                        {{filter.form|crispy}}
                    </div>
                </form>
                <div class="modal-footer">
                    <a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>
                    <button type="submit" class="btn btn-outline-secondary" form="filter">検索</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>

    <div class="row" >
        <div class="col-12">
            {% include "./_pagination.html" %}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for unyou in unyou_list %}
                <li class="list-group-unyou">
                    <div class="row">
                        <div class="col-3">
                            <p>会社名</p>
                        </div>
                        <div class="col-9">
                            <p>{{ unyou.company_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>LBC</p>
                        </div>
                        <div class="col-9">
                            <p>{{unyou.lbc}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                <a class="btn btn-outline-secondary " href="{% url 'detail' unyou.pk %}">詳細</a>
                                <a class="btn btn-outline-secondary " href="{% url 'update' unyou.pk %}">編集</a>
                                <a class="btn btn-outline-secondary " href="{% url 'delete' unyou.pk %}">削除</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-unyou">
                    対象のデータがありません
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row" >
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

staging/unyou/templates/unyou/unyou_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">データ入力</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}